build: false

environment:
    PYTHON_HOME: "C:\\Python37"

    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15

install:
    - set PATH=%PYTHON_HOME%;%PYTHON_HOME%/Scripts/;%PATH%
    - pip.exe install conan --upgrade
    - pip.exe install conan_package_tools bincrafters_package_tools
    - conan user
    - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
    - python make.py conan install_profiles

test_script:
    - python make.py target windows_app conan
    - python make.py target windows_app build
    - python make.py target windows_app package
