build: false

environment:
    PYTHON: "C:\\Python37"

    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

install:
    - set PATH=%PYTHON%;%PYTHON%/Scripts/;%PATH%
    - pip.exe install conan --upgrade
    - conan user
    - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
    - python make.py conan install_profiles

test_script:
    - python make.py target windows_app conan
    - python make.py target windows_app build
    - python make.py target windows_app package
